# Generated by Django 5.2.8 on 2026-09-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='companyDefault', max_length=200),
            preserve_default=False,
        ),
    ]
