# Generated by Django 5.0 on 2026-09-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='recruiter',
            new_name='company',
        ),
        migrations.AddField(
            model_name='job',
            name='onSite',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='salaryRange',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='visaSponsorship',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
