# Generated by Django 5.0 on 2026-09-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_recruiter_job_company_job_onsite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
