# Generated by Django 5.0 on 2026-09-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='salaryRange',
        ),
        migrations.AddField(
            model_name='job',
            name='maxSalary',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='minSalary',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
