# Generated by Django 5.0 on 2026-09-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('applicant', 'Applicant'), ('recruiter', 'Recruiter')], max_length=20),
        ),
    ]
