# Generated by Django 5.0 on 2026-09-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_type',
            new_name='userType',
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='fullName',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
