# Generated by Django 5.0 on 2026-09-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_applicantprofile_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='location',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='projects',
            field=models.IntegerField(default=0),
        ),
    ]
