# Generated by Django 5.0 on 2026-09-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_applicantprofile_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='fullName',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
