# Generated by Django 5.0 on 2026-09-24 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_applicantprofile_fullname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecruiterProfile',
        ),
    ]
