# Generated by Django 5.2.8 on 2026-09-25 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_applicantprofile_user_and_more'),
        ('accounts', '0005_applicantprofile_location_applicantprofile_projects'),
    ]

    operations = [
    ]
