# Generated by Django 5.0 on 2026-09-26 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_recruiterprofile'),
        ('accounts', '0006_merge_20260925_1310'),
    ]

    operations = [
    ]
