# Generated by Django 5.2.8 on 2026-09-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20260925_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='fullName',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
